FROM amazonlinux:2

RUN yum update -y && \
    amazon-linux-extras install nginx1 -y && \
    yum install -y telnet

COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
